#!/bin/sh -eu

touch /var/lock/my_init.lock

echo ""
echo "\033[0;36m*******************************************************************************\033[0m"
echo "\033[0;36mConfiguration applied, starting webserver and PHP.\033[0m"
echo "\033[0;36m*******************************************************************************\033[0m"
echo ""
