#!/bin/bash -eu
# Bash supports the ${!...} construct for indirect variable expansion

requireConfig () {
	if [ -z ${!1:-} ]; then
		echo "Error: $1 is unset" >&2
		exit 1
	fi
}

if [ -z "${APP_KEY_FILE:-}" ]; then
	requireConfig APP_KEY
else
	if [ ! -f "$APP_KEY_FILE" ]; then
		echo "Error: APP_KEY_FILE not found at ${APP_KEY_FILE}" >&2
		exit 1
	fi

	APP_KEY=$(head -n 1 "$APP_KEY_FILE" | tr -d ' ')
	sed -i '/^APP_KEY/d' /opt/librenms/.env
	echo "APP_KEY=$APP_KEY" >> /opt/librenms/.env
	echo "export APP_KEY=\"$APP_KEY\"" >> /etc/librenms_environment
fi

requireConfig DB_HOST
requireConfig DB_USER

if [ -z "${DB_PASS_FILE:-}" ]; then
	requireConfig DB_PASS
else
	if [ ! -f "$DB_PASS_FILE" ]; then
		echo "Error: DB_PASS_FILE not found at ${DB_PASS_FILE}" >&2
		exit 1
	fi

	# Unlike APP_KEY, DB_PASS is loaded inside config.php and therefore not written to .env here
	DB_PASS=$(head -n 1 "$DB_PASS_FILE" | tr -d ' ')
	echo "export DB_PASS=\"$DB_PASS\"" >> /etc/librenms_environment
fi

requireConfig DB_NAME
requireConfig BASE_URL

if [[ "$BASE_URL" == https://* ]]; then
	echo "SESSION_SECURE_COOKIE=true" >> /opt/librenms/.env
	echo "export SESSION_SECURE_COOKIE=true" >> /etc/librenms_environment
fi

# Generate Laravel .env file
COMPOSER_PROCESS_TIMEOUT=3600 APP_ENV=local /sbin/setuser librenms composer run-script post-install-cmd -d /opt/librenms

# Not deleting the directory causes validation errors in LibreNMS
rm -rf /opt/librenms/.composer
