#!/bin/sh -e

if [ -n "$TZ" ]; then
	ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "$TZ" > /etc/timezone

	if [ ! -f /etc/php/8.2/cli/conf.d/100-timezone.ini ]; then
		echo "date.timezone=${TZ}" > /etc/php/8.2/cli/conf.d/100-timezone.ini
	fi

	if [ ! -f /etc/php/8.2/fpm/conf.d/100-timezone.ini ]; then
		echo "date.timezone=${TZ}" > /etc/php/8.2/fpm/conf.d/100-timezone.ini
	fi
fi
