#!/bin/bash -eu

if [ ! -f /opt/librenms/logs/.gitignore ]; then
	cp /opt/helpers/default_files/logs/.gitignore /opt/librenms/logs/.gitignore
fi

if [ ! -f /opt/librenms/rrd/.gitignore ]; then
	cp /opt/helpers/default_files/rrd/.gitignore /opt/librenms/rrd/.gitignore
fi
