#!/bin/bash -e

LOCK_FILE=/etc/my_init_locks.d/1_php.lock

if [ -f "$LOCK_FILE" ]; then
	exit 0
fi

function requireConfig() {
	if [ -z ${!1} ]; then
		echo "Error: $1 is unset"
		exit 1
	fi
}

requireConfig DB_HOST
requireConfig DB_USER
requireConfig DB_PASS
requireConfig DB_NAME
requireConfig BASE_URL

if [ -f /opt/librenms/config.custom.php ]; then
	cat /opt/librenms/config.custom.php >> /opt/librenms/config.php
fi

if [ ! -d /run/php ]; then
	mkdir /run/php
fi

touch "$LOCK_FILE"
