#!/bin/bash -e

function requireConfig() {
	if [ -z ${!1} ]; then
		echo "Error: $1 is unset"
		exit 1
	fi
}

requireConfig DB_HOST
requireConfig DB_USER
requireConfig DB_PASS
requireConfig DB_NAME
requireConfig BASE_URL

cp /opt/librenms/config.docker.php /opt/librenms/config.php

if [ -f /opt/librenms/config.custom.php ]; then
	cat /opt/librenms/config.custom.php >> /opt/librenms/config.php
fi
