#!/bin/bash

function requireConfig() {
	if [ -z ${!1} ]; then
		echo "Error: $1 is unset"
		exit 1
	fi
}

requireConfig DB_HOST
requireConfig DB_USER
if [ -z "$DB_PASS_FILE" ]; then
    requireConfig DB_PASS
fi
requireConfig DB_NAME
requireConfig BASE_URL

if [ -f /opt/librenms/config.custom.php ]; then
	echo -e "\033[1;33mWARNING: Detected deprecated config.custom.php file, please check the docs\033[0m" >&2

	echo "<?php" > /opt/librenms/conf.internal.d/config.custom.php
	cat /opt/librenms/config.custom.php >> /opt/librenms/conf.internal.d/config.custom.php
	chown librenms:librenms /opt/librenms/conf.internal.d/config.custom.php
fi
