#!/bin/bash -e

LOCK_FILE=/var/lock/0_rrdcached.lock

if [ -f "$LOCK_FILE" ]; then
	exit 0
fi

if [ "$RRDCACHED_ENABLE" = "false" ]; then
	rm -rf /etc/service/rrdcached
fi

if [ "$NGINX_ENABLE" = "false" ]; then
        rm -rf /etc/service/nginx
fi

if [ "$PHPFPM_ENABLE" = "false" ]; then
        rm -rf /etc/service/php-fpm
fi

touch "$LOCK_FILE"
