#!/bin/bash -e

LOCK_FILE=/var/lock/librenms_environment.lock

if [ -f "$LOCK_FILE" ]; then
	exit 0
fi

function addConfig() {
	if [ -n "${!1}" ]; then
		echo "export $1=\"${!1}\"" >> /etc/librenms_environment
	fi
}

addConfig APP_KEY
addConfig DB_HOST
addConfig DB_PORT
addConfig DB_USER
addConfig DB_PASS
addConfig DB_PASS_FILE
addConfig DB_NAME
addConfig BASE_URL
addConfig MEMCACHED_ENABLE
addConfig MEMCACHED_HOST
addConfig MEMCACHED_PORT
addConfig DISCOVERY_ENABLE
addConfig DISCOVERY_THREADS
addConfig DAILY_ENABLE
addConfig DAILY_ON_STARTUP
addConfig ALERTS_ENABLE
addConfig POLL_BILLING_ENABLE
addConfig BILLING_CALCULATE_ENABLE
addConfig CHECK_SERVICES_ENABLE
addConfig POLLERS_ENABLE
addConfig RRDCACHED_ENABLE
addConfig RRDCACHED_CONNECT
addConfig RRDCACHED_LISTEN
addConfig NGINX_ENABLE
addConfig PHPFPM_ENABLE
addConfig WEATHERMAP_ENABLE
addConfig WEATHERMAP_CRON

touch "$LOCK_FILE"
