#!/bin/bash -e

LOCK_FILE=/var/lock/librenms_services.lock

if [ -f "$LOCK_FILE" ]; then
	exit 0
fi

if [ "$RRDCACHED_ENABLE" = "false" ]; then
	rm -rf /etc/service/rrdcached
fi

if [ "$NGINX_ENABLE" = "false" ]; then
	rm -rf /etc/service/nginx
fi

if [ "$PHPFPM_ENABLE" = "false" ]; then
	rm -rf /etc/service/php-fpm
fi

if [ "$SNMPTRAPD_ENABLE" != "true" ]; then
	rm -rf /etc/service/snmptrapd
fi

if [ "$LIBRENMS_SERVICE_ENABLE" != "true" ]; then
	rm -rf /etc/service/librenms-service
fi

touch "$LOCK_FILE"
