#!/bin/bash -eu

echo "Starting rrdcached..."

rm -rf /var/run/rrdcached.pid

exec rrdcached \
	-g \
	-w 1800 \
	-z 1800 \
	-f 3600 \
	-s librenms \
	-U librenms \
	-G librenms \
	-B \
	-R \
	-j /var/tmp \
	-t 4 \
	-F \
	-b /opt/librenms/rrd \
	-l "$RRDCACHED_LISTEN"
